---
name: Variable-OnDestruct
version: 0.02
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Call a subroutine on destruction of a variable.
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Variable-OnDestruct
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0
requires:
  perl: 5.007003
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::More: 0
provides:
  Variable::OnDestruct:
    file: lib/Variable/OnDestruct.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - destructor
